# Generated by Django 3.1.2 on 2020-10-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='myfile',
        ),
    ]
