# Generated by Django 3.1.2 on 2020-10-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysafe', '0002_auto_20201001_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='media/files/encrypted'),
        ),
    ]
