# Generated by Django 3.1.2 on 2020-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysafe', '0003_auto_20201020_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='myfile',
            name='title',
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='files/encrypted'),
        ),
    ]
