# Generated by Django 3.1.2 on 2020-10-23 19:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysafe', '0004_auto_20201020_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/files/ecrypted'), upload_to=''),
        ),
    ]
