# Generated by Django 3.1.2 on 2020-10-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysafe', '0005_auto_20201023_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(upload_to='files/encrypted'),
        ),
    ]
