# Generated by Django 3.1.2 on 2020-10-23 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysafe', '0006_auto_20201023_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decryptedFile', models.FileField(upload_to='files/decrypted')),
                ('password', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
